default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: slack_desk_swap_development

test:
  <<: *default
  database: slack_desk_swap_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
