---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: slack-desk-swap-web
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: slack-desk-swap
        component: web
        layer: application
      name: slack-desk-swap-web
    spec:
      containers:
      - name: slack-desk-swap-web
        envFrom:
        - configMapRef:
            name: slack-desk-swap-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/slack-desk-swap:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: slack-desk-swap
    component: web
    layer: application
  name: slack-desk-swap-web
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::585031190124:server-certificate/2018-01-17_artsy-net-wildcard"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    name: https
    targetPort: 8080
  - port: 80
    protocol: TCP
    name: http
    targetPort: 8080
  selector:
    app: slack-desk-swap
    component: web
    layer: application
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: slack-desk-swap-start-round-cron
spec:
  schedule: 0 15 * * 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: slack-desk-swap-timely-extracts-cron
            image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/slack-desk-swap:staging
            command: ["bundle", "exec", "rake", "desk_swap:start_today_round"]
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: slack-desk-swap-environment
          restartPolicy: Never
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 1
                preference:
                  matchExpressions:
                  - key: tier
                    operator: In
                    values:
                    - background
